// <auto-generated />
namespace BlogApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class add_comment_table_and_relation_post : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_comment_table_and_relation_post));
        
        string IMigrationMetadata.Id
        {
            get { return "202411301643412_add_comment_table_and_relation_post"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
