// <auto-generated />
namespace BlogApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class add_relation_post_category : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_relation_post_category));
        
        string IMigrationMetadata.Id
        {
            get { return "202411301635285_add_relation_post_category"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
