// <auto-generated />
namespace BlogApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class making_as_optional_update_date_post_table : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(making_as_optional_update_date_post_table));
        
        string IMigrationMetadata.Id
        {
            get { return "202411270454072_making_as_optional_update_date_post_table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
